### ISSUE TITLE
hrt.prefab.Box is missing in hide

### ISSUE THREAD

**Issue by CrazyFlasher** [josuigoa/hide_example#1]
haxe hide-plugin.hxml
src/prefab/ColorBox.hx:5: characters 24-38 : Type not found : hrt.prefab.Box
PS C:\Users\admin\Desktop\hide_example-master>

**Comment by CrazyFlasher** [comment]
https://github.com/josuigoa/hide_example/pull/2

**Comment by josuigoa** [comment]
merged
